name: "\U0001F41B Nightly Bug"
description: "Report a bug in the Nightly version of Scratch Addons"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "# Does this bug also happen in regular Scratch Addons? If so, report the bug [here](https://github.com/ScratchAddons/ScratchAddons/issues/new?assignees=&labels=type%3A+bug%2C+status%3A+needs+triage&template=---bug.md&title=) instead."

  - type: checkboxes
    id: "verify"
    attributes:
      label: "Are you sure that this doesn't also happen in regular Scratch Addons?"
      options:
        - label: "Yes"
          required: true
  - type: input
    id: "version"
    attributes:
      label: "Nightly version"
      description:
        "Open the extension popup and enter the version number that appears.
        **If the popup doesn't say \"Nightly\" before the version number, [https://github.com/ScratchAddons/ScratchAddons/issues/new?assignees=&labels=type%3A+bug%2C+status%3A+needs+triage&template=---bug.md&title=](please submit your bug report here instead)."
      placeholder: "Example: Nightly 02-08-22"
    validations:
      required: true
  - type: input
    id: "browser"
    attributes:
      label: "Browser"
      description: "Specify both the browser name and the version number."
      placeholder: "Example: Firefox 98"
    validations:
      required: true
  - type: input
    id: "os"
    attributes:
      label: "Operating system"
      description: "Specify both the name and the version number."
      placeholder: "Example: Windows 10"
    validations:
      required: true
  - type: textarea
    id: "description"
    attributes:
      label: "Description"
      description: "What's not working the way you expect it to? What is it doing instead?"
    validations:
      required: true
  - type: textarea
    id: "repro"
    attributes:
      label: "Example scenario"
      description: "What are the steps someone else can take to reproduce the bug? Please be as specific as possible. You can also link to a live example."
    validations:
      required: true
  - type: textarea
    id: "screenshots"
    attributes:
      label: "Screenshots"
      description: "If you have any screenshots of the issue, please include them here."
    validations:
      required: false
  - type: textarea
    id: "console"
    attributes:
      label: "Console errors"
      description: "Go to the page where you're experiencing the issue and press `Ctrl+Shift+K`. If there are any red errors, please copy or screenshot them, then submit them here."
    validations:
      required: false
  - type: markdown
    attributes:
      value: "Thanks for helping us improve Scratch Addons Nightly!"