blank_issues_enabled: false
contact_links:
  - name: 💬 Discuss Nightly
    url: https://github.com/lisa-wolfgang/ScratchAddons/discussions
    about: Get help or ask a question about Nightly
  - name: 🔼 Go back to regular Scratch Addons
    url: https://github.com/ScratchAddons/ScratchAddons/issues/new/choose
    about: Create an issue or browse resources for the main Scratch Addons repository
